#!/bin/env python

import signal
import subprocess
import time
from threading import Thread

from components.battery import Battery
from components.brightness import Brightness
from components.datetime import DateTime
from components.ram import Ram
from components.uptime import Uptime
from components.volume import Volume
from components.weather import Weather
from components.wifi import Wifi
from components.keyboard import Keyboard
from dwm_status_events import add_changed_event_listener, on_signal_callbacks
from status2d import Status2d

status_list = [
    Weather("Costa+Rica"),
    Uptime(),
    Keyboard(),
    Wifi(),
    Ram(),
    DateTime()
]

bundle = [Volume(), Brightness(), Battery()]

sep = ' | '


def update_status():
    name = ''
    info = ''
    for stat in status_list:
        value = str(stat)
        if value == '':
            continue
        name += value + sep

    for stat in bundle:
        value = str(stat)
        if value == '':
            continue
        info += Status2d.offset(0 if info == "" else 5) + value

    subprocess.run(
        ["xsetroot", "-name", f" {name}{info}{Status2d.offset(15)}"])


def on_change():
    update_status()


def on_signal(_x, _y):
    for callback in on_signal_callbacks:
        Thread(callback())


if __name__ == "__main__":
    add_changed_event_listener(on_change)
    signal.signal(signal.SIGUSR1, on_signal)
    update_status()
